/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.debtaccounting.model;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Currency;
import java.util.List;
import java.util.Locale;
import javax.persistence.Basic;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * @author slavb
 */

@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Account implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    /**
     * Наименование счета
     */
    @Basic
    private String name;

    /**
     * Остаток на счете
     */
    @Embedded
    private Money amount;

    @OneToMany(mappedBy = "account")
    @XmlTransient
    private List<DebtAccount> debtAccounts;

    @OneToMany(mappedBy = "account")
    @XmlTransient
    private List<Entry> entries;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Account withId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get наименование счета
     *
     * @return {@link #name}
     */
    public String getName() {
        return name;
    }

    /**
     * Set наименование счета
     *
     * @param name {@link #name}
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Set наименование счета
     *
     * @param name {@link #name}
     * @return {@link #Account}
     */
    public Account withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get остаток на счете
     *
     * @return {@link #amount}
     */
    public Money getAmount() {
        Money money = new Money();
        money.setAmount(0);
        money.setCurrency(Currency.getInstance(Locale.getDefault()));
        for(Entry entry : getEntries()){
            money.addMoney(entry.getAmount());
        }
        return money;
    }

    /**
     * Set остаток на счете
     *
     * @param amount {@link #amount}
     */
    public void setAmount(Money amount) {
        this.amount = amount;
    }

    /**
     * Set остаток на счете
     *
     * @param amount {@link #amount}
     * @return {@link #Account}
     */
    public Account withAmount(Money amount) {
        this.amount = amount;
        return this;
    }

    public List<DebtAccount> getDebtAccounts() {
        if (debtAccounts == null) {
            debtAccounts = new ArrayList<>();
        }
        return debtAccounts;
    }

    public void setDebtAccounts(List<DebtAccount> debtAccounts) {
        this.debtAccounts = debtAccounts;
    }

    public Account withDebtAccounts(List<DebtAccount> debtAccounts) {
        this.debtAccounts = debtAccounts;
        return this;
    }

    public void addDebtAccount(DebtAccount debtAccount) {
        getDebtAccounts().add(debtAccount);
        debtAccount.setAccount(this);
    }

    public void removeDebtAccount(DebtAccount debtAccount) {
        getDebtAccounts().remove(debtAccount);
        debtAccount.setAccount(null);
    }

    public List<Entry> getEntries() {
        if (entries == null) {
            entries = new ArrayList<>();
        }
        return entries;
    }

    public void setEntries(List<Entry> entries) {
        this.entries = entries;
    }

    public Account withEntries(List<Entry> entries) {
        this.entries = entries;
        return this;
    }

    public void addEntry(Entry entry) {
        getEntries().add(entry);
        entry.setAccount(this);
    }

    public void removeEntry(Entry entry) {
        getEntries().remove(entry);
        entry.setAccount(null);
    }

    /**
     * Withdraw money from account
     *
     * @param amount
     * @param target
     * @param date
     */
    void withdraw(Money amount, Account target, LocalDate date) {
        new Transaction(date, amount, this, target).execute();
    }

    /**
     * Deposit money to account
     *
     * @param amount
     * @param source
     * @param date
     */
    public void deposit(Money amount, Account source, LocalDate date) {
        new Transaction(date, amount, source, this).execute();
    }

}