/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.debtaccounting.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * Хозяйствующий субъект
 *
 * @author slavb
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class BusinessEntity implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    @Basic
    private String name;

    @OneToMany(mappedBy = "businessEntity")
    @XmlTransient
    private List<DebtRight> debtRights;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public BusinessEntity withId(Long id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BusinessEntity withName(String name) {
        this.name = name;
        return this;
    }

    public List<DebtRight> getDebtRights() {
        if (debtRights == null) {
            debtRights = new ArrayList<>();
        }
        return debtRights;
    }

    public void setDebtRights(List<DebtRight> debtRights) {
        this.debtRights = debtRights;
    }

    public BusinessEntity withDebtRights(List<DebtRight> debtRights) {
        this.debtRights = debtRights;
        return this;
    }

    public void addDebtRight(DebtRight debtRight) {
        getDebtRights().add(debtRight);
        debtRight.setBusinessEntity(this);
    }

    public void removeDebtRight(DebtRight debtRight) {
        getDebtRights().remove(debtRight);
        debtRight.setBusinessEntity(null);
    }

}