/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.debtaccounting.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * @author slavb
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class CashFlow implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    @OneToMany(mappedBy = "cashFlow")
    @XmlTransient
    private List<Transaction> transactions;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public CashFlow withId(Long id) {
        this.id = id;
        return this;
    }

    public List<Transaction> getTransactions() {
        if (transactions == null) {
            transactions = new ArrayList<>();
        }
        return transactions;
    }

    public void setTransactions(List<Transaction> transactions) {
        this.transactions = transactions;
    }

    public CashFlow withTransactions(List<Transaction> transactions) {
        this.transactions = transactions;
        return this;
    }

    public void addTransaction(Transaction transaction) {
        getTransactions().add(transaction);
        transaction.setCashFlow(this);
    }

    public void removeTransaction(Transaction transaction) {
        getTransactions().remove(transaction);
        transaction.setCashFlow(null);
    }

}