/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.debtaccounting.model;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.*;

/**
 * Право на долг
 *
 * @author slavb
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class DebtRight implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    /**
     * Доля
     */
    @Basic
    @Column(scale = 1, precision = 3)
    private BigDecimal share;

    @ManyToOne
    private BusinessEntity businessEntity;

    @ManyToOne
    private Debt debt;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public DebtRight withId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Get доля
     *
     * @return {@link #share}
     */
    public BigDecimal getShare() {
        return share;
    }

    /**
     * Set доля
     *
     * @param share {@link #share}
     */
    public void setShare(BigDecimal share) {
        this.share = share;
    }

    /**
     * Set доля
     *
     * @param share {@link #share}
     * @return {@link #DebtRight}
     */
    public DebtRight withShare(BigDecimal share) {
        this.share = share;
        return this;
    }

    public BusinessEntity getBusinessEntity() {
        return businessEntity;
    }

    public void setBusinessEntity(BusinessEntity businessEntity) {
        this.businessEntity = businessEntity;
    }

    public DebtRight withBusinessEntity(BusinessEntity businessEntity) {
        this.businessEntity = businessEntity;
        return this;
    }

    public Debt getDebt() {
        return debt;
    }

    public void setDebt(Debt debt) {
        this.debt = debt;
    }

    public DebtRight withDebt(Debt debt) {
        this.debt = debt;
        return this;
    }

}