/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.debtaccounting.model;

import java.io.Serializable;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.xml.bind.annotation.*;
import ru.ilb.debtaccounting.exceptions.AccountNotFoundException;

/**
 * Событие выдачи
 *
 * @author slavb
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@DiscriminatorValue("1")
public class DisbursementEvent extends Event implements Serializable {

    /**
     * Исполнить событие
     * 1. Создать и исполнить транзакцию выдачи
     */
    @Override
    public void execute() {
        Account debit = getDebt().getDebtAccount(DebtBalance.class).map(db -> db.getAccount()).orElseThrow(AccountNotFoundException::new);
        SimpleTransaction simpleTransaction = new SimpleTransaction(debit, null);
        addTransaction(simpleTransaction);
        simpleTransaction.execute();
    }

}