/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.debtaccounting.model;

import java.io.Serializable;
import javax.xml.bind.annotation.*;

/**
 * @author slavb
 */
@XmlAccessorType(XmlAccessType.FIELD)
public class EventRequest implements Serializable {

}