/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.debtaccounting.model;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.*;

/**
 * Транзакция
 *
 * @author slavb
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class Transaction implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    /**
     * Дата транзакции
     */
    @Basic
    private LocalDate date;

    @Basic
    private TransactionStatusCode status;


    /**
     * Сумма
     */
    @Embedded
    private Money amount;

    @ManyToOne
    private Event event;

    @ManyToOne
    private Cashflow cashflow;

    @ManyToOne
    private Account accountFrom;

    @ManyToOne
    private Account accountTo;

    @OneToMany(mappedBy = "transaction")
    @XmlTransient
    private List<Entry> entries;

    public Transaction(LocalDate date, Money amount, Account accountFrom, Account accountTo) {
        this.date = date;
        this.amount = amount;
        this.accountFrom = accountFrom;
        this.accountTo = accountTo;
        this.status = TransactionStatusCode.CREATED;
    }

    public Transaction() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public TransactionStatusCode getStatus() {
        return status;
    }

    public void setStatus(TransactionStatusCode status) {
        this.status = status;
    }

    public Money getAmount() {
        return amount;
    }

    public void setAmount(Money amount) {
        this.amount = amount;
    }

    public Event getEvent() {
        return event;
    }

    public void setEvent(Event event) {
        this.event = event;
    }

    public Cashflow getCashflow() {
        return cashflow;
    }

    public void setCashflow(Cashflow cashflow) {
        this.cashflow = cashflow;
    }

    public Account getAccountFrom() {
        return accountFrom;
    }

    public void setAccountFrom(Account accountFrom) {
        this.accountFrom = accountFrom;
    }

    public Account getAccountTo() {
        return accountTo;
    }

    public void setAccountTo(Account accountTo) {
        this.accountTo = accountTo;
    }

    public List<Entry> getEntries() {
        if (entries == null) {
            entries = new ArrayList<>();
        }
        return entries;
    }

    public void setEntries(List<Entry> entries) {
        this.entries = entries;
    }

    public void addEntry(Entry entry) {
        getEntries().add(entry);
        entry.setTransaction(this);
    }

    public void removeEntry(Entry entry) {
        getEntries().remove(entry);
        entry.setTransaction(null);
    }

    public void switchStatus() {
        if (LocalDate.now().equals(this.getDate())) {
            this.setStatus(TransactionStatusCode.EXECUTED);
        }
    }

    public void execute() {
        Entry entryFrom = new Entry(date, amount.negateMoney());
        accountFrom.addEntry(entryFrom);
        addEntry(entryFrom);
        Entry entryTo = new Entry(date, amount);
        accountTo.addEntry(entryTo);
        addEntry(entryTo);
        this.switchStatus();
    }

}
