
/**
 * This file was generated by the JPA Modeler
 */
package ru.ilb.debtaccounting.model;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.*;

/**
 * Статус долга
 *
 * @author slavb
 */
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
public class TransactionStatus implements Serializable {

    @Id
    @GeneratedValue
    private Long id;

    /**
     * код
     */
    @Basic
    @Enumerated(EnumType.STRING)
    private TransactionStatusCode code;

    @Basic
    private String name;


    public TransactionStatus(Long id, TransactionStatusCode code, String name) {
        this.id = id;
        this.code = code;
        this.name = name;
    }

    public TransactionStatus() {
        this.code = TransactionStatusCode.fromValue(1);
    }

    public TransactionStatus(Long id){
        this.id=id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get код
     *
     * @return {@link #code}
     */
    public TransactionStatusCode getCode() {
        return this.code;
    }

    /**
     * Set код
     *
     * @param code {@link #code}
     */
    public void setCode(TransactionStatusCode code) {
        this.code = code;
    }

    /**
     * Set код
     *
     * @param code {@link #code}
     * @return {@link #DebtStatus}
     */
    public  TransactionStatus withCode(TransactionStatusCode code) {
        this.code = code;
        return this;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public TransactionStatus withName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final DebtStatus other = (DebtStatus) obj;
        if (!java.util.Objects.equals(this.getCode(), other.getCode())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getCode());
        return hash;
    }

}